-- AlterTable
ALTER TABLE `order_status_history` MODIFY `status` ENUM('NEW', 'PAYMENT_VERIFIED', 'ASSIGNED_TO_PICKER', 'PICKING_IN_PROGRESS', 'READY_FOR_DELIVERY', 'READY_FOR_PICKUP', 'ASSIGNED_TO_DRIVER', 'OUT_FOR_DELIVERY', 'DELIVERED', 'PICKED_UP_BY_CUSTOMER', 'COMPLETED', 'CONFIRMED', 'CANCELLED', 'REJECTED') NOT NULL;

-- AlterTable
ALTER TABLE `orders` ADD COLUMN `completedAt` DATETIME(3) NULL,
    ADD COLUMN `fulfillmentType` ENUM('DELIVERY', 'PICKUP') NOT NULL DEFAULT 'DELIVERY',
    ADD COLUMN `pickedUpAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('NEW', 'PAYMENT_VERIFIED', 'ASSIGNED_TO_PICKER', 'PICKING_IN_PROGRESS', 'READY_FOR_DELIVERY', 'READY_FOR_PICKUP', 'ASSIGNED_TO_DRIVER', 'OUT_FOR_DELIVERY', 'DELIVERED', 'PICKED_UP_BY_CUSTOMER', 'COMPLETED', 'CONFIRMED', 'CANCELLED', 'REJECTED') NOT NULL DEFAULT 'NEW',
    MODIFY `paymentMethod` ENUM('CASH_ON_DELIVERY', 'BANK_TRANSFER', 'PAY_AT_BRANCH') NOT NULL;

-- CreateIndex
CREATE INDEX `orders_fulfillmentType_idx` ON `orders`(`fulfillmentType`);
